services:
  findmyfundings:
    build: .
    container_name: findmyfundings
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./pyproject.toml:/app/pyproject.toml:ro
      - ./src:/app/src:ro
      - ./scripts:/app/scripts/:ro
      - db-data:/app/data
    ports:
      - 8000:8000
    command: uv run fastapi dev --host 0.0.0.0

volumes:
  db-data:
